name: Get MTV URL

on:
  push:
    branches:
      - main
  workflow_dispatch:      # Enable manual triggering      

jobs:
  get_mtv_url:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Python script
        run: |
          cd py  # Change directory to where the script is located
          python videohgtv.py > mtvurl.txt  # Run the script and redirect output
