name: VideoTVA

on:
  schedule:
    - cron: '0 */3 * * *'  # Run every 6 hours
  workflow_dispatch:      # Enable manual triggering


jobs:
  generate_m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python Script videotva
        run: python py/videotva.py > fr/videotva.m3u8

      - name: Fetch M3U8 Content with Curl
        run: |
          input_url=$(cat fr/videotva.m3u8)
          full_url=$(echo $input_url | awk -F'index.m3u8' '{print $1}')
          curl -s "$input_url" | grep -oE 'https?://[^'\''"]+' | xargs -I {} curl -s "{}?_=$(date +%s)" | sed 's/\\.m3u8/\\/$full_url&/g'> fr/videotvafull.m3u8

      - name: Run Python Script videoqub
        run: python py/videoqub.py > fr/videoqub.m3u8     

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update token"
          branch: main
          files: |
            fr/videotva.m3u8 fr/videoqub.m3u8
        env:
          GITHUB_TOKEN: ${{ secrets.ROTANA_TOKEN }}
