name: VideoTVA

on:
  schedule:
    - cron: '0 */3 * * *'  # Run every 6 hours
  workflow_dispatch:      # Enable manual triggering


jobs:
  generate_m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

#      - name: Run Python Script videotva
#        run: python py/videotva.py > fr/videotva.m3u8

      - name: Run Python Script videotva
        run: |
         python_output=$(python py/videotva.py)
         echo "#EXTM3U" > fr/videotva.m3u8
         echo "#EXT-X-VERSION:7" >> fr/videotva.m3u8
         echo "#EXT-X-INDEPENDENT-SEGMENTS" >> fr/videotva.m3u8
         echo "#EXT-X-STREAM-INF:BANDWIDTH=8000000,CODECS=\"avc1.4d402a,mp4a.40.2\",RESOLUTION=1920x1080,FRAME-RATE=50,AUDIO=\"audio-mp4a.40.2\",CLOSED-CAPTIONS=NONE" >> fr/videotva.m3u8
         echo "$python_output" >> fr/videotva.m3u8


      - name: Run Python Script videoqub
        run: python py/videoqub.py > fr/videoqub.m3u8 

      - name: Run Python Script videolci
        run: |
         python_output=$(python py/videolci.py)
         echo "#EXTM3U" > fr/videolci.m3u8
         echo "#EXT-X-VERSION:7" >> fr/videolci.m3u8
         echo "#EXT-X-INDEPENDENT-SEGMENTS" >> fr/videolci.m3u8
         echo "#EXT-X-STREAM-INF:BANDWIDTH=8000000,CODECS=\"avc1.4d402a,mp4a.40.2\",RESOLUTION=1920x1080,FRAME-RATE=50,AUDIO=\"audio-mp4a.40.2\",CLOSED-CAPTIONS=NONE" >> fr/videolci.m3u8
         echo "$python_output" >> fr/videolci.m3u8        

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update token"
          branch: main
          files: |
            fr/videotva.m3u8 fr/videoqub.m3u8
        env:
          GITHUB_TOKEN: ${{ secrets.ROTANA_TOKEN }}
