name: Run Script Every 6 Hours

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:      # Enable manual triggering

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create ar Folder
        run: mkdir -p ar  

      - name: Pull Changes from Remote
        run: git pull origin main        

      - name: Run Script and Generate M3U8 for rotana_Clip
        run: |
          id="rotana_Clip"
          id2="rotana_Clip"
          curl_output=$(curl -s "https://rotana.net/en/channels#/live/$id" | grep -oP "id=\"$id2\"[^>]*onclick=\"[^\"]*'\''\Khttps?://[^'\'']*" | grep -oE 'https?://[^'\''"]+' | xargs -I {} curl -s "{}?_=$(date +%s)" | grep -oP "(?<=o=\[)[^\]]+(?=])" | tr -d "'," | base64 -d | grep -o '"streamUrl":\s*"[^"]*"' | awk -F '"' '{print $4}' | sed 's/playlist\.m3u8/rotana\/clip_720p\/chunks.m3u8/g' | head -n 1)
          echo "#EXTM3U" > ar/rotanaclip.m3u8
          echo "#EXT-X-VERSION:7" >> ar/rotanaclip.m3u8
          echo "#EXT-X-INDEPENDENT-SEGMENTS" >> ar/rotanaclip.m3u8
          echo "#EXT-X-STREAM-INF:BANDWIDTH=8000000,CODECS=\"avc1.4d402a,mp4a.40.2\",RESOLUTION=1920x1080,FRAME-RATE=50,AUDIO=\"audio-mp4a.40.2\",CLOSED-CAPTIONS=NONE" >> ar/rotanaclip.m3u8
          echo "$curl_output" >> ar/rotanaclip.m3u8

      - name: Run Script and Generate M3U8 for rotana_CinemaKSA
        run: |
          id="rotana_CinemaKSA"
          id2="rotana_cinemaksa"
          curl_output=$(curl -s "https://rotana.net/en/channels#/live/$id" | grep -oP "id=\"$id2\"[^>]*onclick=\"[^\"]*'\''\Khttps?://[^'\'']*" | grep -oE 'https?://[^'\''"]+' | xargs -I {} curl -s "{}?_=$(date +%s)" | grep -oP "(?<=o=\[)[^\]]+(?=])" | tr -d "'," | base64 -d | grep -o '"streamUrl":\s*"[^"]*"' | awk -F '"' '{print $4}' | sed 's/playlist\.m3u8/rotana\/cinema_720p\/chunks.m3u8/g' | head -n 1)
          echo "#EXTM3U" > ar/rotanacinema.m3u8
          echo "#EXT-X-VERSION:7" >> ar/rotanacinema.m3u8
          echo "#EXT-X-INDEPENDENT-SEGMENTS" >> ar/rotanacinema.m3u8
          echo "#EXT-X-STREAM-INF:BANDWIDTH=8000000,CODECS=\"avc1.4d402a,mp4a.40.2\",RESOLUTION=1920x1080,FRAME-RATE=50,AUDIO=\"audio-mp4a.40.2\",CLOSED-CAPTIONS=NONE" >> ar/rotanacinema.m3u8
          echo "$curl_output" >> ar/rotanacinema.m3u8          

      - name: Run Script and Generate M3U8 for rotana_CinemaMasr
        run: |
          id="rotana_CinemaMasr"
          id2="rotana_cinemamasr"
          curl_output=$(curl -s "https://rotana.net/en/channels#/live/$id" | grep -oP "id=\"$id2\"[^>]*onclick=\"[^\"]*'\''\Khttps?://[^'\'']*" | grep -oE 'https?://[^'\''"]+' | xargs -I {} curl -s "{}?_=$(date +%s)" | grep -oP "(?<=o=\[)[^\]]+(?=])" | tr -d "'," | base64 -d | grep -o '"streamUrl":\s*"[^"]*"' | awk -F '"' '{print $4}' | sed 's/playlist\.m3u8/rotana\/cinemamasr_720p\/chunks.m3u8/g' | head -n 1)
          echo "#EXTM3U" > ar/rotanacinemamasr.m3u8
          echo "#EXT-X-VERSION:7" >> ar/rotanacinemamasr.m3u8
          echo "#EXT-X-INDEPENDENT-SEGMENTS" >> ar/rotanacinemamasr.m3u8
          echo "#EXT-X-STREAM-INF:BANDWIDTH=8000000,CODECS=\"avc1.4d402a,mp4a.40.2\",RESOLUTION=1920x1080,FRAME-RATE=50,AUDIO=\"audio-mp4a.40.2\",CLOSED-CAPTIONS=NONE" >> ar/rotanacinemamasr.m3u8
          echo "$curl_output" >> ar/rotanacinemamasr.m3u8                    

      - name: Run Script and Generate M3U8 for rotana_KhaleejiyaKSA
        run: |
          id="rotana_KhaleejiyaKSA"
          id2="rotana_khaleejiyaksa"
          curl_output=$(curl -s "https://rotana.net/en/channels#/live/$id" | grep -oP "id=\"$id2\"[^>]*onclick=\"[^\"]*'\''\Khttps?://[^'\'']*" | grep -oE 'https?://[^'\''"]+' | xargs -I {} curl -s "{}?_=$(date +%s)" | grep -oP "(?<=o=\[)[^\]]+(?=])" | tr -d "'," | base64 -d | grep -o '"streamUrl":\s*"[^"]*"' | awk -F '"' '{print $4}' | sed 's/playlist\.m3u8/rotana\/khaleejiya_720p\/chunks.m3u8/g' | head -n 1) 
          echo "#EXTM3U" > ar/rotanakhaleejiyaksa.m3u8
          echo "#EXT-X-VERSION:7" >> ar/rotanakhaleejiyaksa.m3u8
          echo "#EXT-X-INDEPENDENT-SEGMENTS" >> ar/rotanakhaleejiyaksa.m3u8
          echo "#EXT-X-STREAM-INF:BANDWIDTH=8000000,CODECS=\"avc1.4d402a,mp4a.40.2\",RESOLUTION=1920x1080,FRAME-RATE=50,AUDIO=\"audio-mp4a.40.2\",CLOSED-CAPTIONS=NONE" >> ar/rotanakhaleejiyaksa.m3u8
          echo "$curl_output" >> ar/rotanakhaleejiyaksa.m3u8               

      - name: Run Script and Generate M3U8 for rotana_Classic
        run: |
          id="rotana_Classic"
          id2="rotana_classic"
          curl_output=$(curl -s "https://rotana.net/en/channels#/live/$id" | grep -oP "id=\"$id2\"[^>]*onclick=\"[^\"]*'\''\Khttps?://[^'\'']*" | grep -oE 'https?://[^'\''"]+' | xargs -I {} curl -s "{}?_=$(date +%s)" | grep -oP "(?<=o=\[)[^\]]+(?=])" | tr -d "'," | base64 -d | grep -o '"streamUrl":\s*"[^"]*"' | awk -F '"' '{print $4}' | sed 's/playlist\.m3u8/rotana\/classical_720p\/chunks.m3u8/g' | head -n 1)
          echo "#EXTM3U" > ar/rotanaclassic.m3u8
          echo "#EXT-X-VERSION:7" >> ar/rotanaclassic.m3u8
          echo "#EXT-X-INDEPENDENT-SEGMENTS" >> ar/rotanaclassic.m3u8
          echo "#EXT-X-STREAM-INF:BANDWIDTH=8000000,CODECS=\"avc1.4d402a,mp4a.40.2\",RESOLUTION=1920x1080,FRAME-RATE=50,AUDIO=\"audio-mp4a.40.2\",CLOSED-CAPTIONS=NONE" >> ar/rotanaclassic.m3u8
          echo "$curl_output" >> ar/rotanaclassic.m3u8               

      - name: Run Script and Generate M3U8 for rotana_Drama
        run: |
          id="rotana_Drama"
          id2="rotana_drama"
          curl_output=$(curl -s "https://rotana.net/en/channels#/live/$id" | grep -oP "id=\"$id2\"[^>]*onclick=\"[^\"]*'\''\Khttps?://[^'\'']*" | grep -oE 'https?://[^'\''"]+' | xargs -I {} curl -s "{}?_=$(date +%s)" | grep -oP "(?<=o=\[)[^\]]+(?=])" | tr -d "'," | base64 -d | grep -o '"streamUrl":\s*"[^"]*"' | awk -F '"' '{print $4}' | sed 's/playlist\.m3u8/rotana\/drama_720p\/chunks.m3u8/g' | head -n 1)
          echo "#EXTM3U" > ar/rotanadrama.m3u8
          echo "#EXT-X-VERSION:7" >> ar/rotanadrama.m3u8
          echo "#EXT-X-INDEPENDENT-SEGMENTS" >> ar/rotanadrama.m3u8
          echo "#EXT-X-STREAM-INF:BANDWIDTH=8000000,CODECS=\"avc1.4d402a,mp4a.40.2\",RESOLUTION=1920x1080,FRAME-RATE=50,AUDIO=\"audio-mp4a.40.2\",CLOSED-CAPTIONS=NONE" >> ar/rotanadrama.m3u8
          echo "$curl_output" >> ar/rotanadrama.m3u8                

      - name: Run Script and Generate M3U8 for rotana_Comedy
        run: |
          id="rotana_Comedy"
          id2="rotana_comedy"
          curl_output=$(curl -s "https://rotana.net/en/channels#/live/$id" | grep -oP "id=\"$id2\"[^>]*onclick=\"[^\"]*'\''\Khttps?://[^'\'']*" | grep -oE 'https?://[^'\''"]+' | xargs -I {} curl -s "{}?_=$(date +%s)" | grep -oP "(?<=o=\[)[^\]]+(?=])" | tr -d "'," | base64 -d | grep -o '"streamUrl":\s*"[^"]*"' | awk -F '"' '{print $4}' | sed 's/playlist\.m3u8/rotana\/comedy_720p\/chunks.m3u8/g' | head -n 1)
          echo "#EXTM3U" > ar/rotanacomedy.m3u8
          echo "#EXT-X-VERSION:7" >> ar/rotanacomedy.m3u8
          echo "#EXT-X-INDEPENDENT-SEGMENTS" >> ar/rotanacomedy.m3u8
          echo "#EXT-X-STREAM-INF:BANDWIDTH=8000000,CODECS=\"avc1.4d402a,mp4a.40.2\",RESOLUTION=1920x1080,FRAME-RATE=50,AUDIO=\"audio-mp4a.40.2\",CLOSED-CAPTIONS=NONE" >> ar/rotanacomedy.m3u8
          echo "$curl_output" >> ar/rotanacomedy.m3u8               

      - name: Run Script and Generate M3U8 for rotana_LBC
        run: |
          id="rotana_LBC"
          id2="rotana_lbc"
          curl_output=$(curl -s "https://rotana.net/en/channels#/live/$id" | grep -oP "id=\"$id2\"[^>]*onclick=\"[^\"]*'\''\Khttps?://[^'\'']*" | grep -oE 'https?://[^'\''"]+' | xargs -I {} curl -s "{}?_=$(date +%s)" | grep -oP "(?<=o=\[)[^\]]+(?=])" | tr -d "'," | base64 -d | grep -o '"streamUrl":\s*"[^"]*"' | awk -F '"' '{print $4}' | sed 's/playlist\.m3u8/rotana\/lbc_720p\/chunks.m3u8/g' | head -n 1)
          echo "#EXTM3U" > ar/rotanalbc.m3u8
          echo "#EXT-X-VERSION:7" >> ar/rotanalbc.m3u8
          echo "#EXT-X-INDEPENDENT-SEGMENTS" >> ar/rotanalbc.m3u8
          echo "#EXT-X-STREAM-INF:BANDWIDTH=8000000,CODECS=\"avc1.4d402a,mp4a.40.2\",RESOLUTION=1920x1080,FRAME-RATE=50,AUDIO=\"audio-mp4a.40.2\",CLOSED-CAPTIONS=NONE" >> ar/rotanalbc.m3u8
          echo "$curl_output" >> ar/rotanalbc.m3u8                

      - name: Run Script and Generate M3U8 for rotana_Kids
        run: |
          id="rotana_CinemaMasr"
          id2="rotana_cinemamasr"
          curl_output=$(curl -s "https://rotana.net/en/channels#/live/$id" | grep -oP "id=\"$id2\"[^>]*onclick=\"[^\"]*'\''\Khttps?://[^'\'']*" | sed 's/CinemaMasr/Kids/g; s/439/441/g; s/Cinema Masr/Kids/g; s/cinemamasr/kids/g' | grep -oE 'https?://[^'\''"]+' | xargs -I {} curl -s "{}?_=$(date +%s)" | grep -oP "(?<=o=\[)[^\]]+(?=])" | tr -d "'," | base64 -d | grep -o '"streamUrl":\s*"[^"]*"' | awk -F '"' '{print $4}' | sed 's/playlist\.m3u8/rotana\/kids_720p\/chunks.m3u8/g' | head -n 1)
          echo "#EXTM3U" > ar/rotanakids.m3u8
          echo "#EXT-X-VERSION:7" >> ar/rotanakids.m3u8
          echo "#EXT-X-INDEPENDENT-SEGMENTS" >> ar/rotanakids.m3u8
          echo "#EXT-X-STREAM-INF:BANDWIDTH=8000000,CODECS=\"avc1.4d402a,mp4a.40.2\",RESOLUTION=1920x1080,FRAME-RATE=50,AUDIO=\"audio-mp4a.40.2\",CLOSED-CAPTIONS=NONE" >> ar/rotanakids.m3u8
          echo "$curl_output" >> ar/rotanakids.m3u8

      - name: Pull changes from remote
        run: git pull origin main

      - name: Commit and Push Changes
        env:
         GITHUB_TOKEN: ${{ secrets.ROTANA_TOKEN }}  # Use the stored PAT secret
        run: |
          git config --local user.email "mikekaprielian@vif.com"
          git config --local user.name "Mikekaprielian"
          git add ar/rotanaclip.m3u8 ar/rotanacinema.m3u8 ar/rotanaclassic.m3u8 ar/rotanacomedy.m3u8 ar/rotanadrama.m3u8 ar/rotanalbc.m3u8 ar/rotanacinemamasr.m3u8 ar/rotanakhaleejiyaksa.m3u8 ar/rotanakids.m3u8
          git commit -m "Update tokens"
          git push
