name: VideoEvents and VideoLive M3u

on:
  schedule:
    - cron: '45 3,7,11,15,19,23 * * *'  # Run every 6 hours
  workflow_dispatch:      # Enable manual triggering

jobs:
  generate_m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create en Folder
        run: mkdir -p en     

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install necessary packages
        run: |
          sudo apt-get update    
          sudo apt-get install -y unzip wget
          sudo apt-get install -y libgconf-2-4 
          sudo apt-get install -y chromium-browser
          #wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_123.0.6312.122-1_amd64.deb && sudo apt install -y /tmp/chrome.deb && sudo rm /tmp/chrome.deb
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas webdriver-manager selenium selenium_stealth pytz

      - name: Run Python Script videoevents
        run: |
          python_output=$(python py/videoevents.py)
          echo "$python_output" > en/videoevents.m3u
          echo "$python_output" > en/videoall.m3u

      - name: Run Python Script videoevents
        run: |
          python_output=$(python py/videolivetv.py)
          echo "$python_output" > en/videolivetv.m3u
          echo "$python_output" >> en/videoall.m3u

      - name: Pull changes from remote
        run: git pull origin main

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update token"
          branch: main
          files: |
            en/videoevents.m3u en/videolivetv.m3u en/videoall.m3u
        env:
          GITHUB_TOKEN: ${{ secrets.ROTANA_TOKEN }}
