name: VideoEvents M3u

on:
  schedule:
    - cron: '0 */1 * * *'  # Run every 6 hours
  workflow_dispatch:      # Enable manual triggering


jobs:
  generate_m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create en Folder
        run: mkdir -p en     

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install selenium_stealth


      - name: Run Python Script videoevents
        run: |
         python_output=$(python py/videoevents.py)
         echo "$python_output" > fr/videoevents.m3u

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update token"
          branch: main
          files: |
            en/videoevents.m3u
        env:
          GITHUB_TOKEN: ${{ secrets.ROTANA_TOKEN }}
